// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ApiGatewayListerExpansion allows custom methods to be added to
// ApiGatewayLister.
type ApiGatewayListerExpansion interface{}

// ApiGatewayNamespaceListerExpansion allows custom methods to be added to
// ApiGatewayNamespaceLister.
type ApiGatewayNamespaceListerExpansion interface{}
