// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	apigateway_v1beta1 "github.com/christianwoehrle/apigateway-controller/pkg/apis/apigateway/v1beta1"
	versioned "github.com/christianwoehrle/apigateway-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/christianwoehrle/apigateway-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/christianwoehrle/apigateway-controller/pkg/client/listers/apigateway/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApiGatewayInformer provides access to a shared informer and lister for
// ApiGateways.
type ApiGatewayInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ApiGatewayLister
}

type apiGatewayInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApiGatewayInformer constructs a new informer for ApiGateway type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApiGatewayInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApiGatewayInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApiGatewayInformer constructs a new informer for ApiGateway type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApiGatewayInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApigatewayV1beta1().ApiGateways(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApigatewayV1beta1().ApiGateways(namespace).Watch(options)
			},
		},
		&apigateway_v1beta1.ApiGateway{},
		resyncPeriod,
		indexers,
	)
}

func (f *apiGatewayInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApiGatewayInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *apiGatewayInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apigateway_v1beta1.ApiGateway{}, f.defaultInformer)
}

func (f *apiGatewayInformer) Lister() v1beta1.ApiGatewayLister {
	return v1beta1.NewApiGatewayLister(f.Informer().GetIndexer())
}
