// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/christianwoehrle/apigateway-controller/pkg/apis/apigateway/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApiGateways implements ApiGatewayInterface
type FakeApiGateways struct {
	Fake *FakeApigatewayV1beta1
	ns   string
}

var apigatewaysResource = schema.GroupVersionResource{Group: "apigateway.cw.com", Version: "v1beta1", Resource: "apigateways"}

var apigatewaysKind = schema.GroupVersionKind{Group: "apigateway.cw.com", Version: "v1beta1", Kind: "ApiGateway"}

// Get takes name of the apiGateway, and returns the corresponding apiGateway object, and an error if there is any.
func (c *FakeApiGateways) Get(name string, options v1.GetOptions) (result *v1beta1.ApiGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apigatewaysResource, c.ns, name), &v1beta1.ApiGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ApiGateway), err
}

// List takes label and field selectors, and returns the list of ApiGateways that match those selectors.
func (c *FakeApiGateways) List(opts v1.ListOptions) (result *v1beta1.ApiGatewayList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apigatewaysResource, apigatewaysKind, c.ns, opts), &v1beta1.ApiGatewayList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ApiGatewayList{}
	for _, item := range obj.(*v1beta1.ApiGatewayList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apiGateways.
func (c *FakeApiGateways) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apigatewaysResource, c.ns, opts))

}

// Create takes the representation of a apiGateway and creates it.  Returns the server's representation of the apiGateway, and an error, if there is any.
func (c *FakeApiGateways) Create(apiGateway *v1beta1.ApiGateway) (result *v1beta1.ApiGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apigatewaysResource, c.ns, apiGateway), &v1beta1.ApiGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ApiGateway), err
}

// Update takes the representation of a apiGateway and updates it. Returns the server's representation of the apiGateway, and an error, if there is any.
func (c *FakeApiGateways) Update(apiGateway *v1beta1.ApiGateway) (result *v1beta1.ApiGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apigatewaysResource, c.ns, apiGateway), &v1beta1.ApiGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ApiGateway), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApiGateways) UpdateStatus(apiGateway *v1beta1.ApiGateway) (*v1beta1.ApiGateway, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apigatewaysResource, "status", c.ns, apiGateway), &v1beta1.ApiGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ApiGateway), err
}

// Delete takes name of the apiGateway and deletes it. Returns an error if one occurs.
func (c *FakeApiGateways) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apigatewaysResource, c.ns, name), &v1beta1.ApiGateway{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApiGateways) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apigatewaysResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ApiGatewayList{})
	return err
}

// Patch applies the patch and returns the patched apiGateway.
func (c *FakeApiGateways) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ApiGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apigatewaysResource, c.ns, name, data, subresources...), &v1beta1.ApiGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ApiGateway), err
}
