// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	apigatewayv1beta1 "github.com/christianwoehrle/apigateway-controller/pkg/client/clientset/versioned/typed/apigateway/v1beta1"
	glog "github.com/golang/glog"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	ApigatewayV1beta1() apigatewayv1beta1.ApigatewayV1beta1Interface
	// Deprecated: please explicitly pick a version if possible.
	Apigateway() apigatewayv1beta1.ApigatewayV1beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	apigatewayV1beta1 *apigatewayv1beta1.ApigatewayV1beta1Client
}

// ApigatewayV1beta1 retrieves the ApigatewayV1beta1Client
func (c *Clientset) ApigatewayV1beta1() apigatewayv1beta1.ApigatewayV1beta1Interface {
	return c.apigatewayV1beta1
}

// Deprecated: Apigateway retrieves the default version of ApigatewayClient.
// Please explicitly pick a version.
func (c *Clientset) Apigateway() apigatewayv1beta1.ApigatewayV1beta1Interface {
	return c.apigatewayV1beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.apigatewayV1beta1, err = apigatewayv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		glog.Errorf("failed to create the DiscoveryClient: %v", err)
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.apigatewayV1beta1 = apigatewayv1beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.apigatewayV1beta1 = apigatewayv1beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
